version: 0.2
phases:
  post_build:
    commands:
      - ls
      - pwd
      - zip -r function1.zip lambda_function
      - echo "Updating Lambda function: LambdaFunction"
      - aws lambda update-function-code --function-name Function --zip-file fileb://function1.zip

      
